### ISSUE TITLE
No Wifi

### ISSUE THREAD

**Issue by dhpete** [mpsdskd/LEDWall#1]
Sorry for the trouble, but I cant seem to get connected. Nothing comes up in my networks, no ''my led'', or any ESP device at all. It worked once, went to the set up page and set up my wifi connection and set a static color. Now I would like to change color but cant get to http://192.168.4.1/. Im a newb and pretty sure Im doing something wrong, just cant figure out what. Some one told me to open the jscolor.js or root.js file but I cant seem to open them. Here is what serial monitor shows, so it seems connected 
![Capture](https://user-images.githubusercontent.com/45876124/54923691-219c2480-4ee1-11e9-9459-dc50342ad450.PNG)
then after a few minutes it says '' getting time''

Any help would be great. Thanks

**Comment by mpsdskd** [comment]
So as far as I understood you:
- Put the software on the ESP
- Started the ESP
- Connected to it's own hotspot
    - Did a Wifi scan
    - Connected it to your home Wifi via the web interface

Right?

Now you try to connect to the device with the IP it had in the hotspot mode, but it actually is a client in your home WiFi.
And it printed its own IP to the console output as being "10.10.10.135".
So you can try to connect to it in your browser either on the IP address
    http://10.10.10.135
or via mDNS
    http://ledwall.local

If this does not work, maybe I did not understand correctly, what you did so far.

**Comment by dhpete** [comment]
Thank you for the reply. I will give it a try.

**Comment by dhpete** [comment]
Ok, uploaded LED_wall.ino to board ''Node MCU" , 
ESP shows up in wifi
connect to ESP and it opens the wifi setup page 192.168.4.1
set SSID and password for my router, click save and get ''Credentials Saved
Trying to connect ESP to network.
If it fails reconnect to AP to try again''
Serial monitor gives me this 
![Capture](https://user-images.githubusercontent.com/45876124/55038974-decd7000-4ff8-11e9-89a9-26c8f475ebc8.PNG)
I reconnect my computer to my network, type in http://10.10.10.131 and it never loads and will time out
I tried using Cine-Lights video for instruction https://www.youtube.com/watch?v=E3wuyTViBlI&t=41s
but am unsure what is meant by "ESP8266 sketch data upload"

Sorry for all the trouble.

**Comment by mpsdskd** [comment]
So you can ping the device, because it seems like it has an internet connection - it shows the correct time?
Sketch data upload is basically this: https://raw.githubusercontent.com/esp8266/arduino-esp8266fs-plugin/master/screenshot.png
(Source: https://github.com/esp8266/arduino-esp8266fs-plugin)
And it is a necessary step to get a web interface in your browser.

But even without it you should see some output in your serial monitor if you try to connect to the ESP via your browser.
If this is not the case, then there is another problem.

**Comment by dhpete** [comment]
Thanks for all your help. Im still learning, and you have been great in helping a Newb. Hopefully I got everything worked out.

**Comment by dhpete** [comment]
Finally got it working!!! Thanks for your help, bro. Now, is there a file I
need to edit to set time and time zone? Need to set to Eastern Standard
time.﻿And Thanks for taking the time to help out a Newb :)
REPLY

**Comment by mpsdskd** [comment]
No Problem, have fun :)

Yes, to change the timezone you need to edit the file "TimeThings.h" LL 19-26.
To find out what to input there instead see https://github.com/JChristensen/Timezone .

**Comment by dhpete** [comment]
Thanks. Tried the edit with this
[image: Capture.PNG]

and I get this compile error
[image: Capture.PNG 3.PNG]
[image: Capture.PNG 2.PNG]
Any ideas? Who knew setting up a clock was so complicated? ;) I really do
appreciate your hard work.

**Comment by mpsdskd** [comment]
There seems to be a problem with your image attachments - I cannot see them

**Comment by mpsdskd** [comment]
Also could you please open another issue for this so others with the same problem have a chance if finding this thread then?

**Comment by dhpete** [comment]
Will do. And will get you some pictures after work. Thanks

**Comment by dhpete** [comment]
New issue opened for others. Here are the images of the compile error, and
what I have edited in code
