### ISSUE TITLE
Setting clock and time zone

### ISSUE THREAD

**Issue by dhpete** [mpsdskd/LEDWall#2]
Finally got this project working!! Now I need to set Time/Timezone. Tried to edit lines 19-26 in 
"TimeThings.h", and I get this compile error
![Capture PNG 3](https://user-images.githubusercontent.com/45876124/55288097-a3c49700-5380-11e9-86a7-a166f7a4619b.PNG)
![Capture PNG 2](https://user-images.githubusercontent.com/45876124/55288105-c0f96580-5380-11e9-806f-e40d162ec15c.PNG)
 
This is what I have entered into code

![Capture](https://user-images.githubusercontent.com/45876124/55288117-dec6ca80-5380-11e9-85bc-a7075fbf6721.PNG)

Im still learning, so please be gentle :) 
Any help would be great.

**Comment by mpsdskd** [comment]
I think you took some code from somewhere regarding your timezone. One problem there is, that the variable "local" is absolutely necessary for the project, but does not exist any more after your changes.

What you should do is only changing the 4 lines starting with "TimeChangeRule" and "Timezone" to your needs.

Look again into https://github.com/mpsdskd/LEDWall/blob/master/LED_wall/TimeThings.h
For your needs you only need to uncomment the lines 23-25 and comment out lines 19-21 (hopefully^^, I changed that to your needs).

**Comment by dhpete** [comment]
Ok, went back and changed to this

![Capture PNG 4](https://user-images.githubusercontent.com/45876124/55290399-e26a4980-53a0-11e9-949e-855bed40dd94.PNG)
I get this error
![Capture PNG5](https://user-images.githubusercontent.com/45876124/55290442-6c1a1700-53a1-11e9-963c-78762c9f39ec.PNG)
If I change local = CE.toLocal(now(), &tcr); to local = usEDT.toLocal(now(), &tcr); or local = EDT.toLocal(now(), &tcr); I get

![Capture PNG6](https://user-images.githubusercontent.com/45876124/55290514-2c076400-53a2-11e9-8e8b-aa1a7760088e.PNG)

Sorry for not understanding all the details...Im still learning.

**Comment by mpsdskd** [comment]
Hm, you changed a lot of things....

Maybe you can revert at least TimeThings back to what lies in this git since today and start from this state?

**Comment by mpsdskd** [comment]
So that your TimeThings contains something like this then:

```
//Time Things
#include <Time.h>
#include <Timezone.h>
#define ARRAY_SIZE(x) sizeof(x)/sizeof(x[0])

IPAddress localTimeServerIPs[3] =
{
  IPAddress( 192, 168, 178, 1),
  IPAddress( 192, 168, 2, 1 ),
  IPAddress( 192, 168, 1, 1 )
};
//IPAddress *localtimeServerIP = IPAddress(192, 168, 178, 1);
unsigned int localPort = 2390;      // local port to listen for UDP packets
IPAddress timeServerIP; // time.nist.gov NTP server address
const char* ntpServerName = "time.nist.gov";
const int NTP_PACKET_SIZE = 48; // NTP time stamp is in the first 48 bytes of the message
byte packetBuffer[ NTP_PACKET_SIZE]; //buffer to hold incoming and outgoing packets
//Central European Time (Frankfurt, Paris)
//TimeChangeRule CEST = {"CEST", Last, Sun, Mar, 2, 120};     //Central European Summer Time
//TimeChangeRule CET = {"CET ", Last, Sun, Oct, 3, 60};       //Central European Standard Time
//Timezone CE(CEST, CET);
////EDT/EST
TimeChangeRule EDT = {"EDT", Second, Sun, Mar, 2, -240};     //Central European Summer Time
TimeChangeRule EST = {"EST ", First, Sun, Nov, 2, -300};       //Central European Standard Time
Timezone CE(EDT, EST);
TimeChangeRule *tcr;        //pointer to the time change rule, use to get the TZ abbrev
time_t utc, local;
// A UDP instance to let us send and receive packets over UDP
WiFiUDP udp;
int connection = 100;
```

**Comment by dhpete** [comment]
That did it!!! You are awesome. Thanks for all the help.

**Comment by mpsdskd** [comment]
You're welcome :+1:
